name: Node.js v16 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    #- run: npm ci # Requires npm-shrinkwrap.json
    - run: npm install
    - run: npm run lint
    - run: npm test
