name: Node.js v22 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    #- run: npm ci # Requires npm-shrinkwrap.json
    - run: npm install
    - run: npm run lint
    - run: npm test
